spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pennywise_db
    username: sean
    password: dbdemaria
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key: classpath:security/team1public.pem
          private-key: classpath:security/team1.pem