spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pennywise_db
    username: root
    password: sql
  sql:
    init:
      mode: always
  jackson:
    time-zone: GMT-4
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 869179723470-udakp8abqo615fg4jv0krkarh61n2jrb.apps.googleusercontent.com
            client-secret: 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