# Use a base image that supports Java
#FROM openjdk:11-jre-slim
#FROM tomcat:9.0
#FROM tomcat:8.0-alpine
#FROM amazoncorretto:21.0.0-al2023-headful
FROM amazoncorretto:17-alpine
#FROM amazoncorretto:17.0.8-al2023-headless

# # Set environment variables for Tomcat
# ENV CATALINA_HOME /usr/local/tomcat
# ENV PATH $CATALINA_HOME/bin:$PATH

#WORKDIR "${CATALINA_HOME}/webapps"

# Create a directory for your WAR file

# Copy your jar file into the container
#COPY pennywise.war .
#ADD pennywise.war . 
ADD ./pennywise-oauth/pennywise-oauth.jar /app/pennywise-oauth.jar
RUN chmod 755 /app/pennywise-oauth.jar


# Copy start script
# ADD start_service.sh .
# RUN chmod 755 start_service.sh

# Expose the default Tomcat port (8080)
EXPOSE 8081

# Start Tomcat and deploy your WAR file
#CMD ["catalina.sh", "run"]
#CMD ["java", "-jar", "/app/pennywise.jar", "--server.port=$PORT"]
#CMD ["start_service.sh"]
CMD java -jar app/pennywise-oauth.jar